spring:
  datasource:
    url: jdbc:mysql://129.154.205.5:3306/formveydb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: Formvey1234!
    driver-class-name: com.mysql.cj.jdbc.Driver

  mvc:
    path match:
      matching-strategy: ant_path_matcher

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
#    database-platform: org.hibernate.dialect.H2Dialect

logging:
  level:
    org.hibernate.sql : debug

cloud:
  aws:
    s3:
      bucket: eraofband
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      instanceProfile: true
      access-key: AKIARNTNV6CZZBBIWQMR
      secret-key: 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